p "seed Admin started"

users = User.create([
  {
    email: 'admin1@vvpao.amsterdam',
    first_name: 'Admin',
    tussenvoegsel: '',
    last_name: '1',
    password: 'VVPAO-2019',
    initials: '',
    street: '',
    streetnumber: '',
    postalcode: '',
    city: '',
    phonenumber: '',
    practice_name: '',
    practice_street: '',
    practice_streetnumber: '',
    practice_postalcode: '',
    practice_city: '',
    practice_email: '',
    practice_phonenumber: '',
    website: '',
    admin: true,
    member: false,
    expertise_id: 2413,
    targetaudience_id: 288,
    profile_image_filename: '',
    newregistrations: false,
    waitingperiod: '',
    contract: false,
    buddy: false,
    training_suggestion: '',
    personal_data_public: false,
    practice_data_public: true,
  },
  {
    email: 'admin2@vvpao.amsterdam',
    first_name: 'Admin',
    tussenvoegsel: '',
    last_name: '2',
    password: 'VVPAO-2019',
    initials: '',
    street: '',
    streetnumber: '',
    postalcode: '',
    city: '',
    phonenumber: '',
    practice_name: '',
    practice_street: '',
    practice_streetnumber: '',
    practice_postalcode: '',
    practice_city: '',
    practice_email: '',
    practice_phonenumber: '',
    website: '',
    admin: true,
    member: false,
    expertise_id: 2413,
    targetaudience_id: 288,
    profile_image_filename: '',
    newregistrations: false,
    waitingperiod: '',
    contract: false,
    buddy: false,
    training_suggestion: '',
    personal_data_public: false,
    practice_data_public: true,
  }
])

p "seed Admin finished"
